<<<<<<< HEAD
mongo_uri = "mongodb+srv://sonnguyenhai7:sVyOZuzdCZPC4DDn@cluster0.okt5f.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
=======
OPENAI_API_KEY = 'lm-studio'
base_url = "http://localhost:1234/v1"
mongo_uri = 
>>>>>>> ab57e7d597d9c3c6772f4785ba878c1f2eeb7dd3
